$Lab="ps1-primer"
$Region="SouthCentralUS"
$User="student-lab-01@labscloudacademy.onmicrosoft.com"
$Pass="labAccount1"
$PolicyDefinitionName="lab-policy"
$PolicyAssignmentName="lab-policy-assignment"
$RoleDefinitionName="Lab Role"